// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAjku6udUmKY4RZAi5iZiuASliT2RPnAI',
    appId: '1:323378812920:web:1f7c11dcbf57f221a3a80d',
    messagingSenderId: '323378812920',
    projectId: 'askidayemek-dbed0',
    authDomain: 'askidayemek-dbed0.firebaseapp.com',
    storageBucket: 'askidayemek-dbed0.appspot.com',
    databaseURL: 'https://askidayemek-dbed0-default-rtdb.europe-west1.firebasedatabase.app/',
    measurementId: 'G-8646DNDD3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgZkWY6WPInBL6_x9l-drdjGOvQq2O84',
    appId: '1:323378812920:android:f4b8ca5cde1155a1a3a80d',
    messagingSenderId: '323378812920',
    projectId: 'askidayemek-dbed0',
    storageBucket: 'askidayemek-dbed0.appspot.com',
    databaseURL: 'https://askidayemek-dbed0-default-rtdb.europe-west1.firebasedatabase.app/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOuWmWbv2agrtirwfvtfm9KnnHF5AaTU',
    appId: '1:323378812920:ios:70ecdbd0c7f0e50da3a80d',
    messagingSenderId: '323378812920',
    projectId: 'askidayemek-dbed0',
    storageBucket: 'askidayemek-dbed0.appspot.com',
    iosBundleId: 'com.example.askidayemek2',
    databaseURL: 'https://askidayemek-dbed0-default-rtdb.europe-west1.firebasedatabase.app/'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOuWmWbv2agrtirwfvtfm9KnnHF5AaTU',
    appId: '1:323378812920:ios:125e8b4ac8f45883a3a80d',
    messagingSenderId: '323378812920',
    projectId: 'askidayemek-dbed0',
    storageBucket: 'askidayemek-dbed0.appspot.com',
    iosBundleId: 'com.example.askidayemek2.RunnerTests',
    databaseURL: 'https://askidayemek-dbed0-default-rtdb.europe-west1.firebasedatabase.app/'
  );
}
